name: Rust

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Update rust
        run: rustup update
      - name: Build
        run: cargo build --verbose --features ci
      - name: Run tests
        run: cargo test --verbose --features ci
